-- Supabase / Postgres schema for Sozdav (Создаватель)
-- Run in Supabase SQL Editor to create tables

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id text,
  username text,
  display_name text,
  role text, -- 'master' or 'client'
  about text,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  owner_id bigint references public.users(id),
  title text,
  description text,
  lat numeric,
  lng numeric,
  budget_min numeric,
  budget_max numeric,
  status text default 'open',
  created_at date default current_date
);

create table if not exists public.bids (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  user_id bigint references public.users(id),
  price numeric,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  from_user bigint references public.users(id),
  to_user bigint references public.users(id),
  order_id bigint references public.orders(id),
  rating int,
  text text,
  created_at timestamptz default now()
);

-- Simple index for geo queries
create index if not exists idx_orders_geo on public.orders using gist (point(lng, lat));
